#+TITLE: ENGDATA Notes
#+AUTHOR: Tyrone
#+STARTUP: showall imagelines latexpreview

------

* Type of Data

Study of the population is a *census*. Study of a sample of a population is a *survey*.

Data can either be numerical or categorical. Just because the data points are numbers, it doesn't mean they are numerical (e.g. student ID numbers, years).

The *Delphi technique* is when you send rounds of questionnaires to a panel of experts to reach a consensus.

* Types of Probability Sampling

1. _Simple Random Sampling_: Every member has an equal chance of being selected (e.g. lottery, random number generator)

2. _Cluster Sampling_: The population is divided by clusters, which is often geographical. And entire clusters are randomly selected.

3. _Stratified Sampling_: The population is divided into subgroups (strata) based on shared characteristics and random samples are taken from each strata. 

4. _Systematic Sampling_: Every n-th member of a group is selected.


The point of probability sampling is that each individual has a known, non-zero chance of being selected; minimizing bias and allowing for generalization.

* Types of Non-Probability Sampling

1. _Convenience Sampling_: Individuals are selected for their availability and accessibility.

2. _Voluntary Respone Sampling_: Individuals select themselves.

3. _Purposive/Judgmental Sampling_: The researcher uses their expertise to select a sample that is most useful to the purpose of the research.

4. _Snowball Sampling_: Participants refer other participants.

5. _Quota Sampling_: Selecting a specific number of individuals from different subgroups.

These methods are faster and easier but risks higher bias. Most often used in exploratory research.

* Types of Comparisons

1. _Component comparison_:

2. _Correlation comparison_:

3. _Frequency comparison_:

4. _Item comparison_:

5. _Time series_:

   ------

* Probability

*DEFINING SAMPLE SPACE*:

_Listing/Roster method_: enumerating all elements of the sample space.

_Property/Set-Builder method_: Choosing a property or characteristic common to all sample points and then using this common characteristic to define the sample space.

_Tree Diagram_: Uses a tree data structure to express sequential order of events of an experiment in chronological order.

An *event* is a subset of a sample space.

A *simple event* is an event which only has one outcome.

A *compound event* is an event which consists of more than one outcome and may be decomposed into simple events.

*OPERATIONS ON EVENTS*

_Union_: A U B, set of all events in A or B.

_Intersection_: A & B (should be upside-down U). Set of all events in A and B

_Complement_: A' represents the set of all events not found in A.

*S* represents the sample space. So S' represents all events not in the sample space.

A & B = NULL is *mutually exclusive* or *disjointed*.

