#+TITLE: Logical Gates Design Notes
#+AUTHOR: Tyrone
#+STARTUP: showall latexpreview inlineimages

* Introduction to Digial Electronic (Logic Circuit Design)

** Analog Signal vs Digital Signal

A digital signal is easier to analyze than an analog signal since an analog wave is a Sine wave; it is varies over time:

$$y(t) = A \sin (\omega t + \phi)$$ 

While a digital wave is a square wave, having only two possible values: *ON* or *OFF*.

The 'ON' value is called the '*HIGH* State ' or the '*TRUE* State' or the '*1* State'.

The 'OFF' value is also called the '*LOW* State' or the '*FALSE* State' or the '*0* State'.

'ON' could mean 5V, 2V, or anything really. 'OFF' means 0V.

** Language of the Computer

The number system used is the decimal system (base-10).

Write the *radix* or the base of a number as a subscript for this subject. To specify what base system you're using.

Like this:

$$123_{10} = 123$$

or

$$342.21_{5 }= 97.44_{10} = 97.44$$

To convert from base /r/ to base-10, multiply each digit by the corresponding power of r and get the total sum.

Example:

$$1162.43_{7} = (1 x 7^{3}) + (1 x 7^{2}) + (6 x 7^{1}) + (2 x 7^{0}) + (4 x 7^{-1}) + (3 x 7^{-2}) =  436.63 = 436.63_{10$$}

$$1011_{2} = (1 x 2^{3}) + (0 x 2^{2}) + (1 x 2^{1}) + (1 x 2^{0}) = 8 + 0 + 2 + 1 = 11 = 11_{10}$$

 Remember the binary, octal, and hexadecimal systems.
 
