#+TITLE: Thoughts on Books I Read
#+AUTHOR: Tyrone

* 1984 by George Orwell

I've heard a lot about this book before reading it. It's basically THE dystopian novel; genre-defining. It did not disappoint.

Firstly, I did not expect a love story hiding in the book. There were even sex scenes described. It was a nice surprise. I guess that would have been important to the story. As discussed in the book, the Party wouldn't allow anyone to love anything but itself. So I guess George Orwell had to demonstrate that.

The takeaway I got was how important the control of information is. If the state had absolute control over all records and journalism in a society, it could control the narrative it uses to justify its actions and decisions.

That is why independent journalists and fact-checkers are so important in modern society. While journalism and fact-checking as we know them haven't been around for long, I think they have become critical in the modern world.

Unlike during previous societies and civilizations, information right now can travel instantaneously and spread globally overnight.

That's also a thing I want to discuss. Instead of one state controlling the entire world, 1984 had three states at constant war with each other. Probably. It wouldn't surprise me if the Party made up the other two superpowers just to justify constant war. There was no concrete evidence in the book that the other two states existed.

If the Party controlled the entire world, I think they'd feed different narratives to the different people living in the supposed area that the other superpowers controlled. They could tell the people living in one area that other states were located in the other side of the world and the people living in another area the same thing.

The different peoples wouldn't be able to communicate with each other and determine that the Party is lying because the Party controlled all communications and travel.

I liked how a lot of the Party's actions and reasons were explained by both Goldstein's book and O'Brien. They were doing all that for the sake of keeping power. I would find that believable, to an extent. I think power is just a means to do something. Power in itself is meaningless. It must be used to do something.

I'd believed that people can naturally be lustful for all the power that they can obtain, even if they don't have a specific goal in mind outside obtaining more power. But I don't think that the political elite would be able to maintain that power continuously for generations. Well I say that but the oligarchic Roman Senate was able to cling to power for two thousand years, even surpassing the original state that it started in as an institution. And the Party has an even tighter grip on policy and public opinion than the Senate ever had.

The Party's use of war in the book was insightful. They used war to destroy any material improvement people's daily lives that technological advancements would bring. They used it to justify why everyone was living miserably while wasting resources and manpower on building weapons that would like be dropped on their own cities.

The Party says that they can't have people living contently and fulfilled since then, they'd have the time and leisure to think about other things than absolute obedience to the Party. The Party wants the people to be completely dependent on them.

I also liked that not even the Party could force their "2 + 2 = 5" logic to war and logistics. It is natural that only those who are efficient with their resources and are competent are the ones who'd have an edge during a war. And that's why they still allowed scientific and technological advancements. Which means, that for a small portion of the Party, it was more meritocratic than other parts.

But even a brilliant scientist would still be vaporize if they didn't at least show outward loyalty and obedience.

A concept that fascinated me, and I'm sure other readers, the most was 'doublethink'. It is to accept two contradictory statements equally as reality. I guess the Party wanted the people to help them control themselves.

I also like the conclusion that the general masses would never revolt on their own. They need leaders to get them to rise up. For most of the story, the so-called Proletariat or 'Proles' that composed of the majority of the population were ignorant of what was really happening and indifferent to history or notions of rebellion.

The role religion played was surprisingly minimal. It was remarked that the Proles could have been granted religion if they really wanted it. I thought religion would have been utilized for more control over the people.

What I find incredulous was the level of attention the Party was giving to every little thing everyone did. Just looking at something weirdly could put you on the Secret Police's radar. It does make me think about the whole 'who's watching the watchers?' thing. There's screens and microphones everywhere. There's definitely more of those surveillance devices than those being surveilled. And there's definitely more people that have to be monitored than those doing the monitoring.

I think most of the time, the Secret Police relies on people reporting each other to catch thought-criminals while only assigning watchers to those they deemed high-risk. They wouldn't need to monitor the Secret Police because they're assured that they're absolutely loyal to the Party.

Yes, that would be the efficient thing to do. Aside from military research, the only thing the Party will allow efficiency in would be in the surveillance state.

I've thought about it for a long time. There is basically no chink in the Party's armor. The only way I see the Party ever going down is by civilization collapse or if the higher-ups unilaterally agree to stop the whole thing.



* Blood Meridian by Cormac McCarthy

That was a difficult read. Not just content-wise, though the content can be disturbing at times. What made the book hard to read, for me at least,  was the prose. McCarthy's writing did not use any quotation marks at all! So it can be hard to surmise who exactly is speaking in a dialogue.

It is kind of obvious though when a character is talking as opposed to when the narrator is describing the scene. McCarthy uses convoluted prose along with a pompous vocabulary to narrate the story. This is in stark contrast to how the characters, aside from Judge Holden, talk.

I will admit though, McCarthy's vivid descriptions of the various landscapes in the book were honestly the parts I liked the most.

Improper grammar, Laconic, and incorrectly spelt words are indicative of when the Kid or any of the other members of Glanton's company are speaking. Except the Judge. He used flowery language to make simple concepts appear more complicated than they really are.

I want to discuss probably the most interesting thing about the book: Judge Holden.

Before reading the book, I've first heard of the Judge being described as one of the most evil characters in all of fiction. I can see why. Publicly, he is a sophisticated and cultured man who seems to be able to appreciate the finer things. But really, he is cruel for the sake of cruelty. He straight-up killed children and puppies just because he could; actually, he specifically went out of his way just to kill them. I think it is the contrast of acting civilized in public while actually being barbaric that makes the character so intriguing.

I was really impressed by his cleverness and talent. Especially that time when he was able to make gunpowder from scratch while being hunted down. In the book, it seemed like there was nothing he couldn't do or not have any knowledge about. He really was cultured, being fluent in multiple languages and proficient in all the musical instruments he encountered. He was aware enough to recognize art or important historical & archeological artifacts.

That's what made his deliberate destruction of them more evil. It is one thing that they are mindlessly destroyed by someone ignorant of their value and it is another thing that they are specifically sought out and destroy because of their value.

There really was nothing he couldn't do. He could be stranded in the desert buck-naked but could easily survive and even negotiate for clothes, horses, and supplies from others with nothing.

One of his quotes surprised me: "Whatever exists in creation without my knowledge, exists without my consent." I thought that quote was from the Emperor of Man from /Warhammer 40K/. Most of his speeches and monologues though went over my head. The same I think for most of the people around him.

Glanton is, I think, the second most interesting thing about the book. The first thing that comes to mind when Glanton is brought up is "manly". He seemed like the no-nonsense type of man who's decisive and willing to do anything. The real Stoic-type who didn't flinch when he was about to die. Still a horrible person though.
 
I never rooted for any of the main characters in the book. They've all done terrible things. Even the Kid and Tobin are guilty I think. They also participated in all the murder and scalping. I was actively rooting for the various soldiers trying to bring the company to justice.

I think the most messed-up scenes from the book that really disturbed me was when they cooked and ate that newborn foal. Like they even described how that it still had the mare's milk still in its stomach (?) and that they were passing it around to drink milk.

When that dancing bear was killed was also pretty messed up. When it was shot the first time, it just danced faster. Which tells me that it was probably trained using pain. There was no reason for it to have been killed, though the same can be said for most of the deaths in the book. I also know that circus animals are taken while they're still young from the wild to be trained. So I got the idea that it was essentially still a child and that it thought if it danced fast enough, it could make the pain go away.  The described crying and helplessness further sold the scene.

Weird I felt more empathy for the animals than the people. But I'm definitely sure I'm not alone there. Animals have this sort of innocence, I think, that stems from their overall ignorance. Modern audiences would definitely be more bothered if a dog died in a movie than the main character.


I don't what my main take-away from this book should be. While I do find the Judge's reasoning behind his philosophy logical, I think it's been taken to an extreme. I cannot accept his claim that war is inherent holy or just. I do think it is inevitable and the ultimate test of superiority but I do not think that should be celebrated or glorified.

I think war is inevitable because there has been many confirmed instances of it in the natural world, from between eusocial insects like ants to other primates like Chimpanzees. I'd also consider the fact the different human cultures isolated on different continents all independently waged war against themselves and their neighbors. Heck, I'm pretty sure there's recorded instances of war from prehistoric times.

This definitely won't be lessened in modern times when the interests of nations and institutes are becoming increasingly interconnected and the systems in place would bring about great opportunities for profit when nations do wage war. But I digress.

I have no experience in such matters so, naturally, my opinion or analysis shouldn't be taken seriously by anyone.

The era and setting that the book takes place in is just so different compared to modern times. People, especially a large group, can't just go around murdering and scalping. Well, I hope so. It's definitely true in large, developed nations but there are plenty of places around the world where such violence could happen and not be broadcasted to the world.

That's the reason I think such violence is unlikely in the modern world: how easy it is for information to spread. If a massacre happens in a place like Texas or Mexico, it would make front page news all over the world. Local authorities would immediately take action. People would know to avoid those places. The perpetrators would be hard-pressed to stay undetected in a world teeming with cameras and microphones.

But the same cannot be said for many places. There are entire countries and regions where the infrastructure does not exist to enable such sharing of information. People could commit atrocities and no one would ever find out.

I think. If such places did exist where such things occurred, no one would know. That's kind of the point.

While people can be capable of great evil and cruelty, I'd like to think that we are equally as capable of compassion and kindness, if not more. That is why I think the Judge is ultimately wrong.

I do want to note that the Judge would thrive in the modern world. He could inflict more suffering and perpetuate even greater violence on a scale and intensity incomparable to what he caused in the book if he were to channel his intelligence and talent to reach into the corporate world or even politics.

* Dune by Frank Herbert


* Dracula by Bram Stoker

* Like Water for Chocolate by Laura Esquivel

I first learned of this book from my high school class on 21^{st} century literature when the teacher was discussing magic realism. She had read a chapter from the book and I was very intrigued.

It is a love story told in the format of monthly recipes for traditional Mexican dishes and home remedies. Something I think is worth noting is that while the main character is Tita, the story is being told by her great niece who literally had no impact to the story at all.

The romance itself is of the forbidden kind. Tita's controlling mother prohibits her from getting married but they do end up together at the very end. I wouldn't say it was happy ending. I'm pretty sure they both died at the end.

As for the magic featured in the story, it actually drives a lot of the plot. Actually, it drives most of the plot now that I think about it.

The magic has no rhyme or reason, it is unstructured. It as if the world just reflects whatever Tita is feeling but taking it to the extreme.

It was a short book that read like an fable. There isn't much I could gleam from it that I could say was the key takeaway. Or maybe I wasn't perceptive or thoughtful enough to catch them.

Plots of forbidden love, overbearing mothers, and of family getting in the way are not uncommon. Like Water for Chocolate is made unique by its integration of Mexican culture and


* The Catcher in the Rye by J.D. Salinger


* The Good Earth by Pearl S. Buck


* The Metamorphosis by Franz Kafka

* The Stranger by Albert Camus
