:PROPERTIES:
:ID:       aa9b9403-8b73-4251-8c2d-68561c81827c
:END:
#+title: Exactness
#+STARTUP: showall latexpreview inlineimages

Exactness is a property that indicates that the system has an underlying conserved quantity.

If an equation is exact, there is a single, underlying quantity that governs the function's behavior.
That quantity is represented by the general solution: /f(x, y)/.

* Determining exactness

First, rewrite the equation into the following formula:

$$M(x, y)dx + N(x, y)dy = 0$$

If $\frac{dM}{dy} = \frac{dN}{dx}$, then equation is exact.

$\frac{dM}{dy}$ means to derive function /M(x, y)/ with respect to y.

$\frac{dN}{dx}$ means to derive function /N(x, y)/ with respect to x.


*  Solving for an exact equation

First, choose either /M(x, y)/ or /N(x, y)/.

**  M(x, y)

1. Integrate function /M(x, y)/ with respect to x. Remember to treat /y/ as a constant.

2. Instead of adding constant /C/, add an unknown function of /y/: /g(y)/.

   $$f(x,y) = \int M(x,y) dx + g(y)$$

3. Differentiate with respect to /y/. This should equate to the original /N(x, y)/.

   $$\frac{df}{dy} = \frac{d(\int M(x,y) dx)}{dy} + g'(y) = N(x, y)$$

4. Isolate /g'(y)/. /N(x, y)/ should cancel out nicely with the rest of the equation.

   $$g'(y) = N(x,y) - \frac{d(\int M(x,y) dx)}{dy}$$

5. Integrate /g'(y)/ with respect to /y/ to find /g(y)/.

   $$g(y) = \int ( N(x, y) - \frac{d(\int M(x,y) dx)}{dy} ) dy $$

6. Obtain /f(x,y)/ using /g(y)/.

   $$f(x,y) = \int M(x,y)dx + g(y)$$

   Implicit solution:

   $$f(x,y) = C$$

** N(x,y)

1. Integrate function /N(x, y)/ with respect to y. Remember to treat /x/ as a constant.

2. Instead of adding constant /C/, add an unknown function of /x: /g(x)/.

   $$f(x,y) = \int N(x,y) dx + g(x)$$

3. Differentiate with respect to /y/. This should equate to the original /N(x, y)/.

   $$\frac{df}{dx} = \frac{d(\int N(x,y) dy)}{dx} + g'(x) = M(x, y)$$

4. Isolate /g'(x)/. /M(x, y)/ should cancel out nicely with the rest of the equation.

   $$g'(x) = M(x,y) - \frac{d(\int N(x,y) dy)}{dx}$$

5. Integrate /g'(x)/ with respect to /x to find /g(x)/.

   $$g(x) = \int ( M(x, y) - \frac{d(\int N(x,y) dy)}{dx} ) dx $$

6. Obtain /f(x,y)/ using /g(x)/.

   $$f(x,y) = \int N(x,y)dx + g(x)$$

   Implicit solution:

   $$f(x,y) = C$$
