:PROPERTIES:
:ID:       891e7dbb-88bb-452c-8420-f279fb449a25
:END:
#+title: Homogeneity
#+STARTUP: showall latexpreview

#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt]

#+LATEX_HEADER: \usepackage[a4paper,margin=0.75in, top=0.85in]{geometry}
#+LATEX_HEADER: \usepackage{amsmath,amssymb,mathtools}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{mathpazo}

#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
#+LATEX_HEADER: \titleformat{\subsection}{\normalize\bfseries}{}{0em}{}

#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{noitemsep, topset=4pt}

#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \pretitle{\begin{center}\large\bfseries}
#+LATEX_HEADER: \posttitle{\end{center}}


#+OPTIONS: toc:t num:t

* In First-Order ODEs (Function Scaling)

A firt-order ODE in the form: $\frac{dy}{dx} = f(x,y)$ is considered homogeneous if the function f(x,y) depends on the ration $\frac{y}{x}$ .

*To test for homogeneity:*

$$f(tx, ty) = t^{n} f(x,y)$$

A function is homogeneous of degree /n/ if both variables are able to be scaled by constant /t/ and yields the original function multiplied by t^{n}.

If the function is rewritten in:

$$M(x,y)dx + N(x,y)dy = 0$$

The function is homogeneous if the *degree* of /M(x,y)/ and /N(x,y)/ are equal.

_For example_:

$$(x^{2} + y^{2})dx + xydy = 0$$

This function is homogeneous.

Individually, x^{2} and y^{2} both have degree of 2.

/xy/ also has degree of 2. As x^{1} \times y^{1} = /xy/.

*EVERY TERM IS DEGREE 2.*

- If the degrees are mixed, that is not homogeneous.

- *You must also inspect the variables.*

- If the variables /x/ and /y/ always appear to be grouped together as a fraction, the function is homogeneous.

  
_Examples_:

- \( \frac{x}{y} \)

- \( \frac{y}{x} \)

- \( \sin\left(\frac{x}{y}\right) \)


Homogeneous first-order equations *cannot have standalone numbers added or subtracted*.
This is becuase constants break the scaling property.

$\frac{dy}{dx} = \frac{x + y}{x}$ is homogeneous.

$\frac{dy}{dx} = \frac{x + y + 1}{x}$ is not homogeneous.

** Solving First-Order ODEs

The idea to solve any first-order ODE is to simplify it by substituting the ratio of x and y.

$v = \frac{y}{x}$ \to $y = vx$

Remember that:


\begin{align}
v &= \frac{y}{x} \\
y &= vx \\
y' &= v * 1 + x * v' \\
\frac{dy}{dx} &= v + x\frac{dv}{dx}
\end{align}


Substitute these values into the original equation.

Then to apply *separation of variables.* Before converting /v/ back to the ratio.


* Homogeneity in Linear ODEs (Structure and Form)

A linear ODE is homogeneous if every term contains the dependent variable or one of its derivatives *AND* if the equation is set to 0.

It can generally be written as:

\[
a_n(x)y^{n} + a_{n-1}(x)y^{n-1}+...+a_1_{}(x)y'+ a_0_{}(x)y = 0
\]

There can be *no forcing term*.

If /y = 0/ is a valid solution, it is homogeneous.

If y_{1} and y_{2} are solutions to a linear homogeneous ODE, then any linear combination of $C_1 y_1 + C_2 y_2$ is also a solution.

*To solve*:

If the coefficients are constant, use a characteristic polynomial.



