:PROPERTIES:
:ID:       891e7dbb-88bb-452c-8420-f279fb449a25
:END:
#+title: Homogeneity
#+STARTUP: showall latexpreview

* In First-Order ODEs (Function Scaling)

A firt-order ODE in the form: $\frac{dy}{dx} = f(x,y)$ is considered homogeneous if the function f(x,y) depends on the ration $\frac{y}{x}$ .

*To test for homogeneity:*

$$f(tx, ty) = t^{n} f(x,y)$$

A function is homogeneous of degree /n/ if both variables are able to be scaled by constant /t/ and yields the original function multiplied by t^{n}.

If the function is rewritten in:

$$M(x,y)dx + N(x,y)dy = 0$$

The function is homogeneous if the *degree* of /M(x,y)/ and /N(x,y)/ are equal.

_For example_:

$$(x^{2} + y^{2})dx + xydy = 0$$

This function is homogeneous.

Individually, x^{2} and y^{2} both have degree of 2.

/xy/ also has degree of 2. As x^{1} \times y^{1} = /xy/.

*EVERY TERM IS DEGREE 2.*

If the degrees are mixed, that is not homogeneous.

You must also inspect the variables.
If the variables /x/ and /y/ always appear to be grouped together as a fraction, the function is homogeneous.

_Examples_:

$$ \frac{x}{y}  ||  \frac{y}{x}$$

$$sin(\frac{x}{y}), cos(\frac{y}{x}), tan(\frac{y}{x})$$

$$ln(y) - ln(x) = ln(\frac{y}{x})$$

$$e^\frac{x}{y}$$


Homogeneous first-order equations *cannot have standalone numbers added or subtracted*.
This is becuase constants break the scaling property.

$\frac{dy}{dx} = \frac{x + y}{x}$ is homogeneous.

$\frac{dy}{dx} = \frac{x + y + 1}{x}$ is not homogeneous.

** Solving First-Order ODEs

The idea to solve any first-order ODE is to simplify it by substituting the ratio of x and y.

$$ v = \frac{y}{x}$$ \to $$y = vx$$

Remember that:

$$y' = v \times 1 + x \times \frac{dv}{dx}$$ \to $$ \frac{dy}{dx} = v + x \frac{dv}{dx}$$

Substitute these values into the original equation.

Then to apply *separation of variables.* Before converting /v/ back to the ratio.


* Homogeneity in Linear ODEs (Structure and Form)

A linear ODE is homogeneous if every term contains the dependent variable or one of its derivatives *AND* if the equation is set to 0.

It can generally be written as:

$$a_{n}(x)y^{n} + a_{n-1}(x)y^{n-1}+..._a_{1}(x)y' + a_{0}(x)y = 0$$

There can be *no forcing term*.

If /y = 0/ is a valid solution, it is homogeneous.

If y_{1} and y_{2} are solutions to a linear homogeneous ODE, then any linear combination of C_{1}y_{1} + C_{2}y_{2} is also a solution.

*To solve*

If the coefficients are constant, use a characteristic polynomial.


See [[id:8fde70c6-a95a-48ac-a958-148064903274][Linear ODEs]]
See [[id:7bff375b-0e2f-432a-8bdc-17ef4a054e58][Linearity]]
