:PROPERTIES:
:ID:       c03618f7-f669-4046-9438-b6970bc5ffb7
:END:
#+TITLE: Diodes
#+AUTHOR: tyrone
#+STARTUP: showall latexpreview
#+LATEX_COMPILER: xelatex

#+LATEX_CLASS_OPTION: [11pt]
#+LATEX_HEADER: \usepackage[a4paper,margin=0.75in,top=0.85in]{geometry}
#+LATEX_HEADER: \usepackage{amsmath,amssymb,mathtools}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \setlength{\parskip}{0.8em}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage{mathpazo}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
#+LATEX_HEADER: \titleformat{\subsection}{\normalsize\bfseries}{}{0em}{}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{noitemsep,topsep=4pt}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \pretitle{\begin{center}\large\bfseries}
#+LATEX_HEADER: \posttitle{\end{center}}
#+OPTIONS: toc:nil num:t

#+FILETAGS: :circuit_physics:components:

* Diodes

By applying voltage to [[id:0abcd92d-5a42-42d7-b286-7aa1d481abce][PN Junctions]], the depleted region shrinks. This is due to the external voltage generating an electric field that opposes the junction's natural electric field.

This causes *carrier injection*: electrons from the N-side and the holes from the P-side are repelled by the battery terminals and are pushed directly into the depleted zone. This will allow current to flow through the *depletion region.*

*A diode is literally just a PN Junction*.

* Bias

_Bias_ is how that external voltage is applied across the junction.

** Forward Bias

Connect the positive terminal of the battery to the P-side and connect the negative terminal to the N-side.

In this configuration, charge carriers can move freely \rightarrow current flows.

Silicon-based diodes need at least *0.7* volts for this to happen..

While germanium-based diodes need at least *0.3* volts.

** Reverse Bias

Connect the battery cathode to the N-side and the connect the battery anode to the P-side.

In this configuration. an electric field is generated that points to the same direction as the natural electric field. This has the effect of strengthening the original field which further pushed electrons to the N-side and holes to the P-side.

Forward bias generates an electric field that points at the opposite direction of the original field. Hence, it's conflicting effect.

The strengthened field causes the depletion region to widen.

But current isn't completely blocked off. A tiny current called the *reverse saturation current* leaks from the minority carriers.

If the applied voltage is too large, the electric field becomes so strong that it rips electrons loose and causes *avalanche multiplication*[fn:1]

This state is called *breakdown*. This does not inherently damage the diode. It is the excessive heat generated by the massive current flow that usually damages the diode.


[fn:1] Search it up.
