q#+TITLE: ENGDATA Notes
#+AUTHOR: Tyrone
#+STARTUP: showall imagelines latexpreview

#+LATEX_HEADER: \usepackage[a4paper,margin=0.75in,top=0.85in]{geometry}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \usepackage{parskip}{0.0em}

#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
#+LATEX_HEADER: \titleformat{\subsection}{\normalize\bfseries}{}{0em}{}

#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{noitemsep, topset=4pt}

#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \pretitle{\begin{center}\large\bfseries}
#+LATEX_HEADER: \posttitle{\end{center}}


#+OPTIONS: toc:t num:t
\begin{document}
------

* Type of Data

Study of the population is a *census*. Study of a sample of a population is a *survey*.

Data can either be numerical or categorical. Just because the data points are numbers, it doesn't mean they are numerical (e.g. student ID numbers, years).

The *Delphi technique* is when you send rounds of questionnaires to a panel of experts to reach a consensus.

* Types of Probability Sampling

1. _Simple Random Sampling_: Every member has an equal chance of being selected (e.g. lottery, random number generator)

2. _Cluster Sampling_: The population is divided by clusters, which is often geographical. And entire clusters are randomly selected.

3. _Stratified Sampling_: The population is divided into subgroups (strata) based on shared characteristics and random samples are taken from each strata. 

4. _Systematic Sampling_: Every n-th member of a group is selected.


The point of probability sampling is that each individual has a known, non-zero chance of being selected; minimizing bias and allowing for generalization.

* Types of Non-Probability Sampling

1. _Convenience Sampling_: Individuals are selected for their availability and accessibility.

2. _Voluntary Response Sampling_: Individuals select themselves.

3. _Purposive/Judgmental Sampling_: The researcher uses their expertise to select a sample that is most useful to the purpose of the research.

4. _Snowball Sampling_: Participants refer other participants.

5. _Quota Sampling_: Selecting a specific number of individuals from different subgroups.

These methods are faster and easier but risks higher bias. Most often used in exploratory research.

* Types of Comparisons

1. _Component comparison_: "How does a part relate to the whole?" (pie chart)

2. _Correlation comparison_: "Do two variables move together?" (scatter plot, bubble chart)

3. _Frequency comparison_: "How many items fall into each range?" (histogram, bell curve)

4. _Item comparison_: "How do things rank against each other?" (bar chart, column chart)

5. _Time series_: "How does something change over time?" (line chart, area chart)
   ------

* Probability

** *Defining Sample Space*

_Listing/Roster method_: enumerating all elements of the sample space.

_Property/Set-Builder method_: Choosing a property or characteristic common to all sample points and then using this common characteristic to define the sample space.

_Tree Diagram_: Uses a tree data structure to express sequential order of events of an experiment in chronological order.

An *event* is a subset of a sample space.

A *sample point* is a specific outcome from the *sample space*.

A *simple event* is an event which only has one outcome.

A *compound event* is an event which consists of more than one outcome and may be decomposed into simple events.

** *Operations on Events*

_Union_: A U B, set of all events in A or B.

_Intersection_: A \cap B. Set of all events in A and B

_Complement_: A' represents the set of all events not found in A.

*S* represents the sample space. So S' represents all events not in the sample space.

A & B = \empty is *mutually exclusive* or *disjointed*.

----------

* Counting Principles and Techniques

** Counting Theory
A set of techniques used for identifying the total number of possibilities of a statistical experiment without enumerating the elements of the sample space.

_Multiplication Rule_:

n_{T} = n_{1} \times n_{2} \times ... \times n_{k}

Where /n/ is an outcome.

_Addition Rule_:
If /k/ outcomes are mutually exclusive, and outcome 1 can be performed in m_{1} ways, outcome 2 can be performed in m_{2} ways, and so on for /k/ outcomes, then the total number of outcomes is given by:

m_{T} = m_{1} + m_{2} + ... + m_{k}


** Simple Permutation

There is an _ordered_ arrangement of *distinct objects*.

The formula:

\[
nPr = \frac{n!}{(n-r)!}
\]

Where /n/ is the total number of objects and /r/ is how many are being selected from /n/.

** Simple Combination

An arrangement of distinct objects _without regard to order_.

\[
nCr = \frac{n!}{(n-r)! * r!}
\]


** Special types of permutation

*** Circular Permutation

Arrangement of objects in a circle.

The formula is:

\[
Pnc = (n-1)!
\]

*** Arrangement of Similar Objects

To find the number of permutations of /n/ "objects" _all taken at the same time_.

- n_{1} are objects of type 1.
- n_{2} are objects of type 2.
- n_{k} are objects of type /k/.

/- n/ represents the total objects.


\[
\sum\limits_{i=1}^{k}^{} n_{i}_{} = n
\]

This translates to:

\[
\frac{n!}{n_{1}! n_{2}! n_{3}! ... n_{k}!}
\]


*** Partitioning of n objects into cells

To find the number of permutations of /n/ "objects" _all taken at the same time_.

- n_{1} are the objects placed in cell 1.
- n_{2} are the objects placed in cell 2.
- n_{k} are the objects placed in cell /k/.

Very similar to the previous type of permutation.


\[
\sum\limits_{i=1}^{k}^{} n_{i}_{} = n
\]

This translates to:

\[
\frac{n!}{n_{1}! n_{2}! n_{3}! ... n_{k}!}
\]



* Axioms of Probability

_Axiom 1_: 0 <= P(A) <= 1.

_Axiom 2_: P(A) = 1 if A is a certain or sure event.

_Axiom 3_: P(A) = 0 if A is an impossible event.

_Axiom 4_: If the probability of events in the sample space is added, the sum is always 1.

\[
\sum\limits_{i=1}^{n} P(E) = 1
\] 


* Ways of measuring probability

** Classical Concept

The probabilities of events can be determined without gathering data.

\[
P(S) = \frac{n(A)}{N}
\]

Where /n(A)/ is the subset of the sample space and /N/ is the total sample space.


** Relative Frequency

Uses historical data or survey results to determine probabilities.

\[
P(A) = \frac{f_{A}}{f_{T}}
\]

Where f_{A} is the frequency of occurance of event A and f_{T} is the total number of observations.

** Subjective Assessment

An expert in the field provides an educated guess of the probability.


* Probability Rules

** Union (A or B)

\[
P(A U B) = P(A) + P(B) - P(A \cap B)
\]

If A and B are mutually exclusive: $P(A U B) = P(A) + P(B)$ 

** Intersection (A and B)

\[
P(A \cap B) = P(A) \times P(B | A)
\]

If A and B are independent: $P(A \cap B) = P(A) \times P(B)$

** Complement of A

\[
P(A') = 1 - P(A)
\]

** Probability of B given A

\[
P(B|A) = \frac{P(A \cap B)}{P(A)}
\]

1. Find the probablity of A and B happening.

2. Divide the probability of both events happening by the probability of event A

If A and B are independent:


$$\begin{align}
P(B|A) &= \frac{P(A \cap B)}{P(A)} \tag{1}\\
P(B) &= \frac{P(A \cap B)}{P(A)} \tag{2}\\
P(B) \cdot P(A) &= P(A \cap B) \tag{3}\\
P(A \cap B) &= P(A) \cdot P(B) \tag{4} 
\end{align}$$

** Venn Diagram

The entire sample space can be expressed as:

\[
P(Sample Space) = P(A \cap B') + P(A' \cap B) + P(A \cap B)  + P(A' \cap B')
\]


** Contingency Table

A tool used to facilitate the calculation of probabilities involving two events.

\begin{table}[h]
\centering
\begin{tabular}{l c c c}
\hline
         & $B$              & $B'$               & Total   \\
\hline
$A$      & $P(A \cap B)$    & $P(A \cap B')$     & $P(A)$  \\
$A'$     & $P(A' \cap B)$   & $P(A' \cap B')$    & $P(A')$ \\
\hline
Total    & $P(B)$           & $P(B')$            & $1$     \\
\hline
\end{tabular}
\end{table}


** Conditional Probability

The probability that an event will occur given that some other event has already occurred.

\[
P(A|B) = \frac{P(A \cap B)}{P(B)}
\]


** Binomial Probability

* Bayes Theorem

Unlike usually where P(effect|cause) is calculated, Bayesian reasoning tries to find P(cause|effect).


\[
P(A | B) = \frac{P(B | A) \times P(A)}{P(B)}
\]

* Random Variable Definition

An item used to define or denote the outcomes in the sample space known as the sample points.
It does this by assigning numerical value to each of outcome in the sample space.
It is an item whose numerical value is of a random nature, and therefore cannot be known with certainty.

** Coin Toss Example:

If you flip a coin three times, define the sample points as the number of heads occur.

| Sample Points | n | Probability |
| HHH           | 3 | 1/8         |
| HHT           | 2 | 1/8         |
| HTH           | 2 | 1/8         |
| HTT           | 1 | 1/8         |
| THH           | 2 | 1/8         |
| TTH           | 1 | 1/8         |
| THT           | 1 | 1/8         |
| TTT           | 0 | 1/8         |

In tabular form, the probability distribution function (p.d.f.) is as follows:

|                n | f(x) |
|                0 | 1/8  |
|                1 | 3/8  |
|                2 | 3/8  |
|                3 | 1/8  |
| Total = \sum f(x) = |  1   |

\[
f(x) = \binom{3}{x} \left(\frac{1}{2}\right)^{3}^{} = \frac{3!}{x!{3-x}!} \cdot \left(\frac{1}{8}\right)
\] 

where x = 0,1,2,3

This equation specifically describes binomial random variable where a fair event is repeated 3 times.

* Types of Random Variable

1. *Discrete* - this type of random variable can only assume a finite or countably infinite number of possible values.

2. *Continuous* - this type of random variable can take on any value within a given range.
   
   - A continuous variable can be converted into a discrete variable.

     - Specify the level of accuracy of measurement

       Ex: Continuous variable: diameter of a ball in inches.
           Discrete variable: diameter of a ball to the nearest tenth of an inch.

     - Introduce Categories to describe the different levels of values of the random variable.

       Ex: Continuous variable: Final grades in terms of raw scores.
           Discrete variable: Final grades converted into 4.0 scale.

* Expectation

The expected value of the random variable x is the _average_ of all possible values of x.
It is one of the properties of a probability distribution.

The notation: $E(x)$ or $\mu_{x}$.

The expectation of x is a weighted average wherein the given probabilities represent the weight.

Example:

\begin{tabular}{|c|c|c|c|c|}
\hline
x & 1 & 2 & 3 & 4 \\
f(x) & 0.5 & 0.3 & 0.1 & 0 \\
\hline
\end{tabular}


\[
E(x) = 1(0.5) + 2(0.3) + 3(0.1) + 4(0.1) = 1.8
\]

For discrete probability distributions: $E(x) = \sum x f(x)$

For continuous probability distribution: $E(x) = \int x f(x) dx$

** Expectation of a Function

If g(x) is a pure function and x is a random variable:

If x is discrete:

\[
E[g(x)] = \mu_{g(x)} = \sum g(x)f(x)
\]

if x is continuous:
\[
E[g(x)] = \mu_{g(x)} = \int_{L}^{U} g(x)f(x) dx
\]

* Variance of Random Variable (\sigma^{2}_{x})

This measures the /dispersion/ or 'spread' of the value x.

This is the average of the squares of the deviations of all the x values from the mean.

The basic formula is: $\sigma^{2}_{x} = E( x - \mu_{x})^{2}$
The working formula is:  $\sigma^{2}_{x} = E(x^{2}) - (\mu_{x})^{2}$
                            $= E(x^{2}) - [E(x)]^{2}$

** Standard Deviation

Converts the variance into the same units as the random variable x.

\[
\sigma_{x} = \sqrt{\sigma^{2}_{x}}
\]

                            
* Laws of Expectation

1. $E(ax + b) = aE(x) + b$
   Consequently: $E(ax) = aE(x)$
                 $E(b) = b$
                 where a, b are constants.

2. $E[g(x) \plusmn h(x)] = E[g(x)] \plusmn E[h(x)]$

3. $E[g(x) \plusmn h(y)] = E[g(x)] \plusmn E[h(y)]$

4. $E(x+y) E(x) + E(y)$

5. $E(x \cdot y) = E(x) \cdot E(y)$ only if x, y are independent variables.



* Laws of Variance

1. $\sigma^{2}_{g(x)} = E{[g(x)]^{2}} - {E[g(x)]}^{2}$

2. $\sigma^{2}_{ax} = a^{2} \cdot \sigma^{2}_{x}$

3. $\sigma^{2}_{b} = 0$

   Consequently: $\sigma^{2}_{ax \plusmn b} = \sigma^{2}_{ax} = a^{2} \cdot \sigma^{2}_{x}$

4. $\sigma^{2}_{ax \plusmn by} = a^{2} \cdot \sigma^{2}_{x} \plus b^{2} \cdot \sigma^{2}_{y}$; only if x and y are independent variables.

5. $\sigma^{2}_{z} = E(z^{2}) - [E(z)]^{2}$; where z = f(x,y) and x, y are independent variables.





* Discrete Probability Distributions

_Probability Distribution_ is a table or a function which helps us determine or compute the probability associated to each value of the random variable.

** Characteristics of a discrete probability distribution

1. f(x) \geq 0 \forall x (for all x)
   
2. \sum f(x) = 1
   
3. P(X = x) = f(x)
   
** Cumulative Distribution Function

A table or a function that determines the probability that the random variable X takes on values that are less than or equal to a specific value x.

It is denoted by:

\[ F(x) = P(X \le x) = \sum_{X=L}^{x} f(x) \]

where L  = lower limit of possible x values


* Types of Discrete Probability Distributions

** Discrete Uniform Distribution

All values of the random variables have an equal chance of occurring.

\[
u (x:n) = \frac{1}{n} ; x = x_{1}, x_{2 }, x_{3}, ... x_{n} 
\]

Where:
- u(x:n) = the probability assigned to each one of the values.
- n = parameter of the distribution referring to the total number of values which the random variable can assume.

  
** Binomial Distribution

The experiment consists of n repeated trials. Each trial is called a *Bernoulli* trial.

For each trial, there are only *two mutually exclusive* outcomes: /success/ and /failure/.

Let p = probability of success and q = probability of failure.
\[
p + q = 1
\]

The probability of success remains constant from trial to trial. The repeated trials are independent.

_Underlying Assumption_ : sampling is done with replacement.

\[
f(x) = b(x, n, p) = \binom{n}{x} p^{x} q^{n-x}
\]
_Mean_ (\mu) : \mu = n \cdot p

_Variance_ (\sigma^{2}) : \sigma^{2} = n \cdot p \cdot q

** Multinomial Distribution

Let x_{1} = number of successes of outcome
i = 1, 2, 3, ..., k

\[ M(x_1, x_2, \dots, x_k, p_1, p_2, \dots, p_k, n) = \frac{n!}{x_1! x_2! \dots x_n!} p_1^{x_1} p_2^{x_2} \dots p_k^{x_k} \]

_Mean_ (\mu) : \mu =


** Negative Binomial Distribution

If repeated independent trials can result in a success with a probability p and a failure with a probability of q = 1 - p, then the probability distribution of the random variable x, the trial on which the k^{th} success occurs is given by

** Geometric Distribution

** Hypergeometric Distribution

** Poisson Distribution



\end{document}
