#+TITLE: ENGDATA Notes
#+AUTHOR: Tyrone
#+STARTUP: showall imagelines latexpreview

#+LATEX_HEADER: \usepackage[a4paper,margin=0.75in,top=0.85in]{geometry}
#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \usepackage{parskip}

#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
#+LATEX_HEADER: \titleformat{\subsection}{\normalize\bfseries}{}{0em}{}

#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{noitemsep, topset=4pt}

#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \pretitle{\begin{center}\large\bfseries}
#+LATEX_HEADER: \posttitle{\end{center}}


#+OPTIONS: toc:t num:t
------

* Type of Data

Study of the population is a *census*. Study of a sample of a population is a *survey*.

Data can either be numerical or categorical. Just because the data points are numbers, it doesn't mean they are numerical (e.g. student ID numbers, years).

The *Delphi technique* is when you send rounds of questionnaires to a panel of experts to reach a consensus.

* Types of Probability Sampling

1. _Simple Random Sampling_: Every member has an equal chance of being selected (e.g. lottery, random number generator)

2. _Cluster Sampling_: The population is divided by clusters, which is often geographical. And entire clusters are randomly selected.

3. _Stratified Sampling_: The population is divided into subgroups (strata) based on shared characteristics and random samples are taken from each strata. 

4. _Systematic Sampling_: Every n-th member of a group is selected.


The point of probability sampling is that each individual has a known, non-zero chance of being selected; minimizing bias and allowing for generalization.

* Types of Non-Probability Sampling

1. _Convenience Sampling_: Individuals are selected for their availability and accessibility.

2. _Voluntary Respone Sampling_: Individuals select themselves.

3. _Purposive/Judgmental Sampling_: The researcher uses their expertise to select a sample that is most useful to the purpose of the research.

4. _Snowball Sampling_: Participants refer other participants.

5. _Quota Sampling_: Selecting a specific number of individuals from different subgroups.

These methods are faster and easier but risks higher bias. Most often used in exploratory research.

* Types of Comparisons

1. _Component comparison_: "How does a part relate to the whole?" (pie chart)

2. _Correlation comparison_: "Do two variables move together?" (scatter plot, bubble chart)

3. _Frequency comparison_: "How many items fall into each range?" (histogram, bell curve)

4. _Item comparison_: "How do things rank against each other?" (bar chart, column chart)

5. _Time series_: "How does something change over time?" (line chart, area chart)
   ------

* Probability

** *Defining Sample Space*

_Listing/Roster method_: enumerating all elements of the sample space.

_Property/Set-Builder method_: Choosing a property or characteristic common to all sample points and then using this common characteristic to define the sample space.

_Tree Diagram_: Uses a tree data structure to express sequential order of events of an experiment in chronological order.

An *event* is a subset of a sample space.

A *sample point* is a specific outcome from the *sample space*.

A *simple event* is an event which only has one outcome.

A *compound event* is an event which consists of more than one outcome and may be decomposed into simple events.

** *Operations on Events*

_Union_: A U B, set of all events in A or B.

_Intersection_: A \cap B. Set of all events in A and B

_Complement_: A' represents the set of all events not found in A.

*S* represents the sample space. So S' represents all events not in the sample space.

A & B = NULL is *mutually exclusive* or *disjointed*.

----------

* Counting Principles and Techniques

** Counting Theory
A set of techniques used for identifying the total number of possibilities of a statistical experiment without enumerating the elements of the sample space.

_Multiplication Rule_:

n_{T} = n_{1} \times n_{2} \times ... \times n_{k}

Where /n/ is an outcome.

_Addition Rule_:
If /k/ outcomes are mutually exclusive, and outcome 1 can be performed in m_{1} ways, outcome 2 can be performed in m_{2} ways, and so on for /k/ outcomes, then the total number of outcomes is given by:

m_{T} = m_{1} + m_{2} + ... + m_{k}


** Simple Permutation

There is an _ordered_ arrangement of *distinct objects*.

The formula:

\[
nPr = \frac{n!}{(n-r)!}
\]

Where /n/ is the total number of objects and /r/ is how many are being selected from /n/.

** Simple Combination

An arrangement of distinct objects _without regard to order_.

\[
nCr = \frac{n!}{(n-r)! * r!}
\]


** Special types of permutation

*** Circular Permutation

Arrangement of objects in a circle.

The formula is:

\[
Pnc = (n-1)!
\]

*** Arrangement of Similar Objects

To find the number of permutations of /n/ "objects" _all taken at the same time_.

- n_{1} are objects of type 1.
- n_{2} are objects of type 2.
- n_{k} are objects of type /k/.

/- n/ represents the total objects.


\[
\sum\limits_{i=1}^{k}^{} n_{i}_{} = n
\]

This translates to:

\[
\frac{n!}{n_{1}! n_{2}! n_{3}! ... n_{k}!}
\]


*** Partitioning of n objects into cells

To find the number of permutations of /n/ "objects" _all taken at the same time_.

- n_{1} are the objects placed in cell 1.
- n_{2} are the objects placed in cell 2.
- n_{k} are the objects placed in cell /k/.

Very similar to the previous type of permutation.


\[
\sum\limits_{i=1}^{k}^{} n_{i}_{} = n
\]

This translates to:

\[
\frac{n!}{n_{1}! n_{2}! n_{3}! ... n_{k}!}
\]



* Axioms of Probability

_Axiom 1_: 0 <= P(A) <= 1.

_Axiom 2_: P(A) = 1 if A is a certain or sure event.

_Axiom 3_: P(A) = 0 if A is an impossible event.

_Axiom 4_: If the probability of events in the sample space is added, the sum is always 1.

\[
\sum\limits_{i=1}^{n} P(E) = 1
\] 


* Ways of measuring probability

** Classical Concept

The probabilities of events can be determined without gathering data.

\[
P(S) = \frac{n(A)}{N}
\]

Where /n(A)/ is the subset of the sample space and /N/ is the total sample space.


** Relative Frequency

Uses historical data or survey results to determine probabilities.

\[
P(A) = \frac{f_{A}}{f_{T}}
\]

Where f_{A} is the frequency of occurance of event A and f_{T} is the total number of observations.

** Subjective Assessment

An expert in the field provides an educated guess of the probability.


* Probability Rules

** Union (A or B)

\[
P(A U B) = P(A) + P(B) - P(A \cap B)
\]

If A and B are mutually exclusive: $P(A U B) = P(A) + P(B)$ 

** Intersection (A and B)

\[
P(A \cap B) = P(A) \times P(B | A)
\]

If A and B are independent: $P(A \cap B) = P(A) \times P(B)$

** Complement of A

\[
P(A') = 1 - P(A)
\]

** Probability of B given A

\[
P(B|A) = \frac{P(A \cap B)}{P(A)}
\]

1. Find the probablity of A and B happening.

2. Divide the probability of both events happening by the probability of event A

If A and B are independent:


$$\begin{align}
P(B|A) &= \frac{P(A \cap B)}{P(A)} \tag{1}\\
P(B) &= \frac{P(A \cap B)}{P(A)} \tag{2}\\
P(B) \cdot P(A) &= P(A \cap B) \tag{3}\\
P(A \cap B) &= P(A) \cdot P(B) \tag{4} 
\end{align}$$

** Venn Diagram

The entire sample space can be expressed as:

\[
P(Sample Space) = P(A \cap B') + P(A' \cap B) + P(A \cap B)  + P(A' \cap B')
\]


** Contingency Table

A tool used to facilitate the calculation of probabilities involving two events.

\begin{table}[h]
\centering
\begin{tabular}{l c c c}
\hline
         & $B$              & $B'$               & Total   \\
\hline
$A$      & $P(A \cap B)$    & $P(A \cap B')$     & $P(A)$  \\
$A'$     & $P(A' \cap B)$   & $P(A' \cap B')$    & $P(A')$ \\
\hline
Total    & $P(B)$           & $P(B')$            & $1$     \\
\hline
\end{tabular}
\end{table}


** Conditional Probability

The probability that an event will occur given that some other event has already occured.

\[
P(A|B) = \frac{P(A\capB)}{P(B)}
\]


** Binomial Probability

* Bayes Theorem

Unlike usualky where P(effect|cause) is calculated, Bayesian reasoning tries to find P(cause|effect).

\[
P(A | B) = \frac{P(B | A) \times P(A)}{P(B)}
\]
